spring.application.name=ApiPapas
server.port=8081

# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:papasdb
spring.h2.console.enabled=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
